import { OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { MatChipInputEvent } from "@angular/material/chips";
import { OnboardingService } from "../onboarding.service";
import { ActivatedRoute, Router } from "@angular/router";
import { CdkDragDrop } from "@angular/cdk/drag-drop";
import { MatDialog } from "@angular/material/dialog";
export declare class TemplateProfileCreateComponent implements OnInit {
    private fb;
    service: OnboardingService;
    private route;
    private router;
    private dialog;
    form: FormGroup;
    validCategory: boolean;
    separatorKeysCodes: number[];
    currentProfil: any;
    canExit: boolean;
    tags: any[];
    id: string;
    parent: any[];
    editIndex: any;
    showProfileName: boolean;
    matIconList: {
        name: string;
    }[];
    isPictoListShow: boolean;
    picto: string;
    conditionData: any[];
    categories: any[];
    constructor(fb: FormBuilder, service: OnboardingService, route: ActivatedRoute, router: Router, dialog: MatDialog);
    defaultCategorie: any;
    canDeactivate(): true | import("rxjs").Subject<boolean>;
    ngOnInit(): Promise<void>;
    onAddNewCategory(e: any): void;
    onAddNewField(...params: any[]): void;
    onAddNewSubLevelField(...params: any[]): void;
    onRemoveField(...params: any[]): void;
    onRemoveCategory(e: any, i: any): void;
    onChangeCategory(): boolean;
    onSubmit(): Promise<void>;
    onChangeType(type: string, ...params: any[]): void;
    onKeyPress(event: any, ...params: any[]): void;
    removeKeyword(keyword: any, ...params: any[]): void;
    onExpendMore(event: any, ...params: any[]): void;
    onCheckedDefault(event: any, ...params: any[]): void;
    addKeywordFromInput(event: MatChipInputEvent, prev: any, ...params: any[]): void;
    drop(event: CdkDragDrop<string[]>): void;
    ingoreDefaultAction(e: any): void;
    onShowCategory(): void;
    onSelectPicto(e: any, picto: any): void;
    onShowPictoList(e: any): void;
    onChangeLabel(event: any, ...params: any[]): void;
    onCheckedChip(event: any, ...params: any[]): void;
    openDialog(): void;
    onPassInEditMode(i: any): void;
    onEdit(): void;
    onEditCategoryName(i: any, name: any): void;
    onAcrelink(e: any): void;
    getConditionValues(): void;
}
