import { ActivatedRoute, Router } from '@angular/router';
import { displayedColumnsInterface } from "ngx-table";
import { OnInit } from '@angular/core';
import { IFilterConfiguration } from 'ngx-filter';
import { DatePipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import { OnboardingService } from '../../onboarding.service';
import * as i0 from "@angular/core";
export declare class OnboardingListComponent implements OnInit {
    private service;
    private router;
    private route;
    private dialog;
    datepipe: DatePipe;
    onboardingList: any;
    inputSearch: string;
    currentLength: number;
    currentFilter: string;
    onboarding: any[];
    accounts: any;
    search: string;
    onboardingFormatList: any[];
    onboardingFinished: any;
    onboardingToFinish: any;
    showSearch: false;
    templates: any[];
    locale: any;
    ngxFilterData: IFilterConfiguration[];
    ngxFilterInit: string;
    columnDefinitions: displayedColumnsInterface[];
    localService: any;
    _loading_table: boolean;
    private HiddenIndex;
    index: number;
    lang: string;
    dataFiltered: any[];
    searchText: string;
    cancelSearch(): void;
    constructor(service: OnboardingService, router: Router, route: ActivatedRoute, dialog: MatDialog, datepipe: DatePipe);
    onFilter(event: any): void;
    onRefresh(event: any): void;
    checkOnboardingPath(): string;
    ngOnInit(): Promise<void>;
    findAccount(account: any): any;
    onForamtList(datas: any): void;
    onFilterTemplate(): void;
    triggerChange($event: any): void;
    openDialog(): void;
    onExportToXLSX(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<OnboardingListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<OnboardingListComponent, "lib-onboarding-list", never, {}, {}, never, never, false>;
}
