import { OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { OnboardingService } from "../onboarding.service";
import { ActivatedRoute, Router } from "@angular/router";
import { CdkDragDrop } from "@angular/cdk/drag-drop";
import { MatDialog } from "@angular/material/dialog";
import * as i0 from "@angular/core";
export declare class OnboardingCreateComponent implements OnInit {
    private fb;
    service: OnboardingService;
    private route;
    private router;
    private dialog;
    form: FormGroup;
    currentProfil: any;
    canExit: boolean;
    tags: any[];
    id: string;
    parent: any[];
    editIndex: any;
    showProfileName: boolean;
    selectedMenu: number;
    templates: any;
    contacts: any;
    matIconList: {
        name: string;
    }[];
    isPictoListShow: boolean;
    picto: string;
    currentOnboarding: any;
    currentTemplate: any;
    isSelected: boolean;
    currentUser: any;
    currentActive: any;
    showMode: boolean;
    constructor(fb: FormBuilder, service: OnboardingService, route: ActivatedRoute, router: Router, dialog: MatDialog);
    categories: any;
    isObject(obj: any): boolean;
    canDeactivate(): true | import("rxjs").Subject<boolean>;
    ngOnInit(): Promise<void>;
    onCreateDynamicForm(): void;
    onSelectContactTemplate(): void;
    onSelect(id: any): void;
    existSubForm(forms: any): boolean;
    onChangeCategory(): any;
    onSubmit(): Promise<void>;
    onExpendMore(event: any, ...params: any[]): void;
    drop(event: CdkDragDrop<string[]>): void;
    ingoreDefaultAction(e: any): void;
    onShowCategory(): void;
    onSelectPicto(e: any, picto: any): void;
    onShowPictoList(e: any): void;
    openDialog(): void;
    isExpanded(forms: any[]): void;
    onCheckConditionLocationValue(iscondition: any, location: any, conditionValue: any): boolean;
    checkSubForm(forms: any): boolean;
    onSelectMenu(i: any): void;
    static ɵfac: i0.ɵɵFactoryDef<OnboardingCreateComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<OnboardingCreateComponent, "create-onboarding", never, {}, {}, never>;
}
