import { OnInit } from '@angular/core';
import { OnboardingService } from '../onboarding.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { CdkDragDrop } from '@angular/cdk/drag-drop';
import { MatChipInputEvent } from '@angular/material/chips';
import { ActivatedRoute } from '@angular/router';
import * as i0 from "@angular/core";
export declare class OnboardingFormComponent implements OnInit {
    service: OnboardingService;
    private fb;
    private route;
    onboardingForm: FormGroup;
    currentUser: any;
    templates: any;
    contacts: any;
    categories: any;
    isSelected: boolean;
    currentOnboarding: any;
    id: string;
    constructor(service: OnboardingService, fb: FormBuilder, route: ActivatedRoute);
    ngOnInit(): Promise<void>;
    onSelectContactTemplate(): void;
    onCreateDynamicForm(): void;
    onPopulateValue(): void;
    onSelect(id: any): void;
    onSelectUser(Id: any): void;
    onAddNewCategory(e: any): void;
    onAddNewField(...params: any[]): void;
    onAddNewSubLevelField(...params: any[]): void;
    onRemoveField(...params: any[]): void;
    onRemoveCategory(e: any, i: any): void;
    onChangeCategory(): any;
    onChangeType(type: string, ...params: any[]): void;
    onKeyPress(event: any, ...params: any[]): void;
    removeKeyword(keyword: string, ...params: any[]): void;
    onExpendMore(event: any, ...params: any[]): void;
    addKeywordFromInput(event: MatChipInputEvent, ...params: any[]): void;
    drop(event: CdkDragDrop<string[]>): void;
    ingoreDefaultAction(e: any): void;
    static ɵfac: i0.ɵɵFactoryDef<OnboardingFormComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<OnboardingFormComponent, "lib-onboarding-form", never, {}, {}, never>;
}
